### PR TITLE
Improve the Login/Register Forms. Add tailwind css

### PR DESCRIPTION
**Pull request by RakinduM**
I added the tailwind css and improved the login and register forms and make them responsive.
As I see someone work on adding tailwind css to whole project, I didn't try to change or remove anything in css files.

### CODE REVIEW

**Comment by vaibhavyadav-dev** [comment]
@RakinduM your change is appreciated but it doesn't fit with overall UI.
Just put dark theme to look good.
Rest is good to go 💯 


image

After successful change I'll merge this

**Comment by RakinduM** [comment]
> @RakinduM your change is appreciated but it doesn't fit with overall UI. Just put dark theme to look good. Rest is good to go 💯
> 
> image
> 
> After successful change I'll merge this

Sure I'll make those changes

**Comment by vaibhavyadav-dev** [comment]
@RakinduM I would appreciate it, if can you make like this 
**NOTE: AI GENERATED IMAGE**


image


This is suggested Upgrade for Healthcare Portal but you can adjust it for Patient/User

**Comment by RakinduM** [comment]
> @RakinduM I would appreciate it, if can you make like this **NOTE: AI GENERATED IMAGE**
> 
> image
> 
> This is suggested Upgrade for Healthcare Portal but you can adjust it for Patient/User

@vaibhavyadav-dev  ok  no problem. So is it needed apply a background image for the whole background instead of dark color?

**Comment by vaibhavyadav-dev** [comment]
> So is it needed apply a background image for the whole background instead of dark color?

@RakinduM Yes, It should cover whole page (background Image) and must be responsive, if possible add dark color else remove it.

**Comment by RakinduM** [comment]
> > So is it needed apply a background image for the whole background instead of dark color?
> 
> @RakinduM Yes, It should cover whole page (background Image) and must be responsive, if possible add dark color else remove it.

Alright.

**Comment by Vardhan-Harsh07** [comment]
@vaibhavyadav-dev 
image
image
i did this too i hope u liked it its simple also its looking good if u like it i can make another issue then you can pull it although i am the guy who is assigned as the designer of homepage which is also i am doing write now

**Comment by vaibhavyadav-dev** [comment]
@RakinduM please fix the scaling issue ( Microsoft Edge ) 


image

**Comment by RakinduM** [comment]
> @RakinduM please fix the scaling issue ( Microsoft Edge )
> 
> image

Fixed it

**Comment by vaibhavyadav-dev** [comment]
@RakinduM your contribution lacks attention, without thinking or testing you commited your changes.

**Pull request merged**
