### PR TITLE
improve ui of login page

### PR DESCRIPTION
**Pull request by matinshaikh31**

### CODE REVIEW

**Comment by vaibhavyadav-dev** [comment]
Good Job @matinshaikh31 !


image



but there are several fixes you must do, before I merge this, 
- Add dark theme to main login panel and background properly so that it matches with overall UI
- Place google (give it proper width) and register button properly
- Since it is User Portal try to add People wearing mask, give it abstract look

Rest is good to go 💯

**Review by vaibhavyadav-dev — CHANGES_REQUESTED** [review]
- Dark theme to support UI
- Responsive ( ignore it if already implemented )
- Fix buttons, proper scaling and resizing

**Review by vaibhavyadav-dev — CHANGES_REQUESTED** [review]
image


- Implement same in Registration Page ( Just Change the Parameter, no need to change the UI )
- Fix Spacing Issue b/w box and labels

After successful completion your PR will be merged 💯

**Review by vaibhavyadav-dev — APPROVED** [review]

**Comment by matinshaikh31** [comment]
Okh

**Comment by vaibhavyadav-dev** [comment]
Great Job @matinshaikh31 !

**Pull request merged**
